from pydantic import BaseModel, Field


class FinancialData(BaseModel):
    ticker: str = Field(..., description="Stock ticker symbol")
    market: str = Field(default="US", description="Market: US or IN")
    currency: str = Field(default="USD", description="Currency code")
    company_name: str = Field(..., description="Full company name")
    sector: str = Field(default="", description="Company sector")
    industry: str = Field(default="", description="Company industry")
    current_price: float | None = Field(None, description="Current stock price")
    market_cap: float | None = Field(None, description="Market capitalization in USD")
    revenue: float | None = Field(None, description="Total revenue in USD")
    revenue_growth: float | None = Field(None, description="Year-over-year revenue growth as a percentage")
    net_income: float | None = Field(None, description="Net income in USD")
    profit_margin: float | None = Field(None, description="Net profit margin as a percentage")
    pe_ratio: float | None = Field(None, description="Price-to-Earnings ratio")
    eps: float | None = Field(None, description="Earnings per share")
    cash: float | None = Field(None, description="Total cash and equivalents in USD")
    debt: float | None = Field(None, description="Total debt in USD")
    debt_to_equity: float | None = Field(None, description="Debt-to-equity ratio")
    free_cash_flow: float | None = Field(None, description="Free cash flow in USD")
    roe: float | None = Field(None, description="Return on equity as a percentage")
    dividend_yield: float | None = Field(None, description="Dividend yield as a percentage")
    fifty_two_week_high: float | None = Field(None, description="52-week high price")
    fifty_two_week_low: float | None = Field(None, description="52-week low price")
    price_to_book: float | None = Field(None, description="Price-to-Book ratio")
    piotroski_score: int | None = Field(None, description="Piotroski F-Score (0-9)")
    piotroski_details: list[str] = Field(default_factory=list, description="F-Score criteria breakdown")
    fundamental_signal: str = Field(default="neutral", description="Fundamental signal: strong, healthy, neutral, weak, distressed")
